services:
  # ─── ZOOKEEPER ─────────────────────────────────────────────────
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.2
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # ─── KAFKA ───────────────────────────────────────────────────────
  kafka:
    image: confluentinc/cp-kafka:7.4.2
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "energy_topic:1:1"
    ports:
      - "9092:9092"

  # ─── POSTGRES FOR AIRFLOW METADATA ──────────────────────────────
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data

  # ─── AIRFLOW DB INITIALIZATION ─────────────────────────────────
  airflow-init:
    image: apache/airflow:2.8.1
    restart: on-failure
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./pipelines/dags:/opt/airflow/dags
      - ./ml/models:/opt/airflow/dags/ml/models
      - ./airflow_logs:/opt/airflow/logs
      - ./airflow_plugins:/opt/airflow/plugins
    entrypoint:
      - bash
      - -c
      - |
        airflow db init

  # ─── AIRFLOW WEBSERVER ──────────────────────────────────────────
  airflow-webserver:
    image: apache/airflow:2.8.1
    restart: unless-stopped
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./pipelines/dags:/opt/airflow/dags
      - ./ml/models:/opt/airflow/dags/ml/models
      - ./airflow_logs:/opt/airflow/logs
      - ./airflow_plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      retries: 3

  # ─── AIRFLOW SCHEDULER ──────────────────────────────────────────
  airflow-scheduler:
    image: apache/airflow:2.8.1
    restart: unless-stopped
    depends_on:
      - airflow-webserver
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./pipelines/dags:/opt/airflow/dags
      - ./ml/models:/opt/airflow/dags/ml/models
      - ./airflow_logs:/opt/airflow/logs
      - ./airflow_plugins:/opt/airflow/plugins
    command: scheduler

  # ─── PROMETHEUS ─────────────────────────────────────────────────
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    depends_on:
      - airflow-webserver
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  # ─── GRAFANA ────────────────────────────────────────────────────
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      # shifted host port to avoid conflict
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro

volumes:
  postgres_db:
