[tool.ruff]
line-length = 100
extend-exclude = ["mlruns", "notebooks", "data", "airflow_logs", "airflow/logs"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E203"]

[tool.ruff.lint.isort]
known-first-party = ["ml", "serving", "pipelines", "kafka_consumer", "iot_simulator", "tests"]
force-sort-within-sections = true
