[tool.ruff]
line-length = 120
extend-exclude = ["mlruns", "notebooks", "data", "airflow_logs", "airflow/logs"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E203"]

[tool.ruff.lint.isort]
known-first-party = ["ml", "serving", "pipelines", "kafka_consumer", "iot_simulator", "tests"]
force-sort-within-sections = true

[tool.ruff.lint.per-file-ignores]
"pipelines/dags/ml_pipeline.py" = ["I001"]

[tool.black]
line-length = 120
extend-exclude = '''
(
  ^notebooks/
  | ^mlruns/
  | ^airflow_logs/
  | ^airflow/logs/
)
'''
